name: Build Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    paths:
      - yolks/**

jobs:
  build:
    name: "yolks:${{ matrix.image }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ["sfml"]

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./yolks/${{ matrix.image }}
          tags: ghcr.io/NimajnebEC/yolks:${{ matrix.image }}
          push: true
